### ISSUE TITLE
[Feature request] Get Pushbullet style notification popups

### ISSUE THREAD

**Issue by ThatLurker** [mskian/gotify-push#2]
As the subject says. How possible would it be to get Pushbullet style notification popups on new messages.

**Comment by mskian** [comment]
Example Please

**Comment by ThatLurker** [comment]
So when you get a new message in Pushbullet you get a notification popup like the one bellow.
It would be cool to get something like that when a new message is send to the gotify server

![Pushbullet-Android-PC-Sync-0](https://user-images.githubusercontent.com/1533244/60772343-b1b35200-a0fd-11e9-819c-ca8d65b7983b.png)

**Comment by jmattheis** [comment]
@pahakalle You mean just the notification? The webui creates these notifications, so if you've a tab with the ui open and allowed the website to create notification, then it should already work.

**Comment by ovizii** [comment]
As far as I see, the notification comes from the push-bullet chrome extension not from any open webui.

**Comment by mskian** [comment]
it's a core related topic better start the discussion on official Gotify repo
