### ISSUE TITLE
push to firefox store

### ISSUE THREAD

**Issue by bayang** [mskian/gotify-push#9]
Hi
Would you agree to also push your extension to the firefox store ?

I tested it and it just works as is on firefox.

The only tweak needed is in debug mode, the storage.sync calls fail because an extension id is not present.

Steps I followed : 

* clone repo
* to allow extension installation in debug mode add the following to the manifest : 
```
"browser_specific_settings": {
        "gecko": {
          "id": "gotify-send@example.com",
          "strict_min_version": "42.0"
        }
      }
```
* in about:debugging#/runtime/this-firefox select "load a temporary extension", pick either the manifest file or zip containing all the source files
* test the extension : it works flawlessly

**Comment by mskian** [comment]
what about local data storage?

**Comment by bayang** [comment]
What do you mean ? Which part should I check ?

The url entered in the settings page is persisted if that is what you want to know.

But after restart of firefox the temporary extension is gone, so I can't check if settings are persisted between restarts.

**Comment by mskian** [comment]
storing API data's - yes entering API URL
I think changes in code required for local data storage

**Comment by bayang** [comment]
I thought it should work as is : 

https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities

**Comment by mskian** [comment]
@bayang - Sorry for late replay
recently start using firefox for works
just port the chrome extension to firefox - https://github.com/mskian/gotify-push-firefox
submitted on mozilla extension store waiting for review and approval

**Comment by mskian** [comment]
Done - https://addons.mozilla.org/en-US/firefox/addon/gotify-push/
